INSERT INTO ng_nts_lookup VALUES (3, 'Phone', 'Best Connection Method', 9);
INSERT INTO ng_nts_lookup VALUES (4, 'Mobile', 'Best Connection Method', 9);
INSERT INTO ng_nts_lookup VALUES (5, 'Mail', 'Best Connection Method', 9);
INSERT INTO ng_nts_lookup VALUES (6, 'Passport', 'Identification Type', 7);
INSERT INTO ng_nts_lookup VALUES (7, 'National ID', 'Identification Type', 7);
INSERT INTO ng_nts_lookup VALUES (8, 'Male', 'Gender', 5);
INSERT INTO ng_nts_lookup VALUES (9, 'Female', 'Gender', 5);
INSERT INTO ng_nts_lookup VALUES (11, 'ENG', 'Salutation', 4);
INSERT INTO ng_nts_lookup VALUES (10, 'DR', 'Salutation', 4);
INSERT INTO ng_nts_lookup VALUES (1, 'active', 'General Status', 3);
INSERT INTO ng_nts_lookup VALUES (2, 'not active', 'General Status', 3);
INSERT INTO ng_nts_lookup VALUES (15, 'House', 'Facility Type', 6);
INSERT INTO ng_nts_lookup VALUES (16, 'MRS', 'Salutation', 4);
INSERT INTO ng_nts_lookup VALUES (17, 'MR', 'Salutation', 4);
INSERT INTO ng_nts_lookup VALUES (12, 'Flat', 'Service Type', 2);
INSERT INTO ng_nts_lookup VALUES (13, 'Usage', 'Service Type', 2);
INSERT INTO ng_nts_lookup VALUES (18, 'New', 'Order Status', 8);
INSERT INTO ng_nts_lookup VALUES (19, 'In Progress', 'Order Status', 8);
INSERT INTO ng_nts_lookup VALUES (20, 'Done', 'Order Status', 8);
INSERT INTO ng_nts_lookup VALUES (21, 'Working', 'Employee Status', 10);
INSERT INTO ng_nts_lookup VALUES (22, 'Fired', 'Employee Status', 10);
INSERT INTO ng_nts_lookup VALUES (23, 'Resigned', 'Employee Status', 10);
INSERT INTO ng_nts_lookup VALUES (24, 'Kilowatt', 'Measurement Units', 1);
INSERT INTO ng_nts_lookup VALUES (25, 'Meter Cubic', 'Measurement Units', 1);
INSERT INTO ng_nts_lookup VALUES (26, 'Mega Byte', 'Measurement Units', 1);
INSERT INTO ng_nts_lookup VALUES (27, 'Hour', 'Measurement Units', 1);
INSERT INTO ng_nts_lookup VALUES (14, 'One Time', 'Service Type', 2);
